name: TODO to Issue

on:
  push:
    branches:
      - master

jobs:
  todo_to_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v4.13